#include <Rendering\TexturesList.h>

const uint16_t finishTexturePixels[TEXTURE_DEFAULT_SIZE * TEXTURE_DEFAULT_SIZE] = 
{
    BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN,
    BACKGROUND_COLOR, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN,
    BACKGROUND_COLOR, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, 
    BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN, COLOR_CYAN,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_WHITE, 
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_WHITE,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_WHITE,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_WHITE,
};

const uint16_t playerTexturePixels[TEXTURE_DEFAULT_SIZE * TEXTURE_DEFAULT_SIZE] = 
{
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, 
    COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE, COLOR_BLUE
};

const uint16_t wallTexturePixels[TEXTURE_DEFAULT_SIZE * TEXTURE_DEFAULT_SIZE] = 
{
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED,
    COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED, COLOR_RED
};

const uint16_t keyTexturePixels[TEXTURE_DEFAULT_SIZE * TEXTURE_DEFAULT_SIZE] = 
{
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
    BACKGROUND_COLOR, COLOR_YELLOW, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
    COLOR_YELLOW, BACKGROUND_COLOR, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, BACKGROUND_COLOR,
    COLOR_YELLOW, COLOR_YELLOW, COLOR_YELLOW, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, COLOR_YELLOW, BACKGROUND_COLOR,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
    BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR,
};

const uint16_t doorTexturePixels[TEXTURE_DEFAULT_SIZE * TEXTURE_DEFAULT_SIZE] = 
{
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN,
    COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN, COLOR_BROWN
};