#pragma once

#define SIZE_MULTIPLIER 8
#define REAL_WIDTH 160
#define REAL_HEIGHT 128

#define MAP_WIDTH REAL_WIDTH / SIZE_MULTIPLIER
#define MAP_HEIGHT REAL_HEIGHT / SIZE_MULTIPLIER
#define STARTER_PLAYER_POSITION_X 3
#define STARTER_PLAYER_POSITION_Y 3
#define MINIMAL_JOYSTICK_DEVIATION_TO_MOVE 300
#define JOYSTICK_READ_MINIMAL_COOLDOWN 100
#define LEVEL_COUNT 4
#define MAX_GAME_OBJECTS_PER_LEVEL 10
#define PLAYER_SIZE_X 1
#define PLAYER_SIZE_Y 1


#define COLOR_BLACK   ST77XX_BLACK//0x0000
#define COLOR_BLUE    ST77XX_BLUE//0x001F
#define COLOR_RED     ST77XX_RED//0xF800
#define COLOR_GREEN   ST77XX_GREEN//0x07E0
#define COLOR_YELLOW  ST77XX_YELLOW//0xFFE0
#define COLOR_WHITE   ST77XX_WHITE//0xFFFF
#define COLOR_ORANGE  ST77XX_ORANGE//0xFD20

#define FPS_TEXT_POSITION_X 105
#define FPS_TEXT_POSITION_Y 5
#define FPS_TEXT_SIZE 1
#define FPS_TEXT_COLOR COLOR_WHITE
#define FPS_BACKGROUND_SIZE_X 46
#define FPS_BACKGROUND_SIZE_Y 10
#define FPS_SHOW_DELAY 500

#define PHYSICS_2D_FALL_DELAY 100